// Dependency-free finance report export: a branded HTML document that can be
// printed to PDF or downloaded as a Word file. No libraries, so nothing to
// install or keep in sync — the same markup drives both formats.

const esc = (v) =>
  v == null
    ? ''
    : String(v).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

/**
 * Builds the report's inner HTML (heading, meta, summary tiles, table).
 * columns: [{ key, label, align }], rows: array of objects keyed by column.key.
 */
const buildBody = ({ title, subtitle, meta = [], summary = [], columns = [], rows = [], note }) => {
  const metaHtml = meta.length
    ? `<div class="meta">${meta.map((m) => `<span><b>${esc(m.label)}:</b> ${esc(m.value)}</span>`).join('')}</div>`
    : '';

  const summaryHtml = summary.length
    ? `<table class="summary"><tr>${summary
        .map((s) => `<td><div class="s-label">${esc(s.label)}</div><div class="s-value">${esc(s.value)}</div></td>`)
        .join('')}</tr></table>`
    : '';

  const head = columns
    .map((c) => `<th style="text-align:${c.align || 'left'}">${esc(c.label)}</th>`)
    .join('');

  const body = rows.length
    ? rows
        .map(
          (r) =>
            `<tr>${columns
              .map((c) => `<td style="text-align:${c.align || 'left'}">${esc(r[c.key])}</td>`)
              .join('')}</tr>`
        )
        .join('')
    : `<tr><td colspan="${columns.length}" class="empty">No records for this period.</td></tr>`;

  return `
    <div class="report">
      <div class="brand">MR&nbsp;<span>BITES</span></div>
      <h1>${esc(title)}</h1>
      ${subtitle ? `<p class="sub">${esc(subtitle)}</p>` : ''}
      ${metaHtml}
      ${summaryHtml}
      <table class="grid">
        <thead><tr>${head}</tr></thead>
        <tbody>${body}</tbody>
      </table>
      ${note ? `<p class="note">${esc(note)}</p>` : ''}
      <p class="foot">Generated by MR Bites · ${esc(new Date().toLocaleString('en-IN'))}</p>
    </div>`;
};

const STYLES = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #0f172a; margin: 0; padding: 32px; }
  .report { max-width: 900px; margin: 0 auto; }
  .brand { font-size: 22px; font-weight: 800; color: #056548; letter-spacing: 1px; }
  .brand span { color: #b59a00; }
  h1 { font-size: 22px; margin: 14px 0 2px; }
  .sub { color: #64748b; margin: 0 0 14px; font-size: 13px; }
  .meta { display: flex; flex-wrap: wrap; gap: 16px; font-size: 12px; color: #475569; margin-bottom: 18px; }
  table.summary { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  table.summary td { border: 1px solid #e2e8f0; padding: 12px 14px; width: 20%; vertical-align: top; }
  .s-label { font-size: 10px; text-transform: uppercase; letter-spacing: .5px; color: #94a3b8; font-weight: 700; }
  .s-value { font-size: 18px; font-weight: 800; margin-top: 4px; }
  table.grid { width: 100%; border-collapse: collapse; font-size: 12px; }
  table.grid th { background: #f1f5f9; text-align: left; padding: 8px 10px; border-bottom: 2px solid #e2e8f0; font-size: 11px; text-transform: uppercase; letter-spacing: .4px; color: #475569; }
  table.grid td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
  table.grid tr:nth-child(even) td { background: #fafcfb; }
  .empty { text-align: center; color: #94a3b8; padding: 24px; }
  .note { font-size: 11px; color: #64748b; margin-top: 16px; }
  .foot { font-size: 10px; color: #94a3b8; margin-top: 28px; text-align: center; }
  @media print { body { padding: 0; } }
`;

/** Opens the report in a new window and triggers the print dialog (Save as PDF). */
export const exportPdf = (report) => {
  const win = window.open('', '_blank');
  if (!win) {
    window.alert('Please allow pop-ups to export the PDF.');
    return;
  }
  win.document.write(
    `<!doctype html><html><head><meta charset="utf-8"><title>${esc(report.title)}</title><style>${STYLES}</style></head><body>${buildBody(report)}</body></html>`
  );
  win.document.close();
  win.focus();
  // Give the new document a tick to lay out before printing.
  setTimeout(() => win.print(), 350);
};

/** Downloads the report as a Word-openable .doc file. */
export const exportDoc = (filename, report) => {
  const html =
    `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">` +
    `<head><meta charset="utf-8"><style>${STYLES}</style></head><body>${buildBody(report)}</body></html>`;
  const blob = new Blob(['﻿', html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.doc') ? filename : `${filename}.doc`;
  a.click();
  URL.revokeObjectURL(url);
};
